version: '3'
services:
  api:
    image: node:16.16.0
    working_dir: /code
    volumes:
      - type: bind
        source: ./Lets_Get_Quizzical_Backend
        target: /code

  db:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=quizzical
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
